os: linux
dist: focal
language: php
php: 8.2

services: postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT: 5433
    - DB_NAME: 'xyz'
    - DB_USER: 'travis'
install: skip
script:
  - psql -U $DB_USER -c "CREATE DATABASE $DB_NAME;"
  - psql -U $DB_USER -c "ALTER USER $DB_USER SET bytea_output = 'escape';"
  - psql -c "\l"
  - psql -c "\du"
