arch: arm64
virt: vm
os: linux
dist: focal

services:
  - docker

install: skip
script:
  - cat /etc/subuid
  - cat /etc/subgid
  - docker pull moussavdb/build-nodejs:lts
  - docker images
jobs:
  include:
    - language: generic
    - language: shell
    - language: ruby
      ruby: 2.7.7
