# .travis.yml
dist: focal

os: linux
language: shell

before_install:
  - sudo apt-get update && sudo apt-get install -y autoconf bison build-essential curl gettext git libgd-dev libcurl4-openssl-dev libedit-dev libicu-dev libjpeg-dev libmysqlclient-dev libonig-dev libpng-dev libpq-dev libreadline-dev libsqlite3-dev libssl-dev libxml2-dev libzip-dev openssl pkg-config re2c zlib1g-dev
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
  - . "$HOME/.asdf/asdf.sh"
  - asdf plugin-add php https://github.com/asdf-community/asdf-php.git
  - asdf install php 8.2.13

script: php --version
