language: shell

before_install:
  - chmod a+x install_gsdk
  - ./install_gsdk
  - export PATH=$PATH:~/google-cloud-sdk/bin

install: skip

script:
  - gcloud version
  - sleep 3
jobs:
  include:
    - os: osx
      osx_image: xcode14.2
    - os: osx
      osx_image: xcode13.2
    - os: osx
      osx_image: xcode12.2
