language: shell
os: linux
dist: jammy
jobs:
  include:
    - addons:
      apt:
        update: true
        packages:
          - redis
      script:
       - redis-cli --version
    - services:
       - redis-server
      script:
       - redis-cli --version
