os: linux
dist: focal

language: shell
install: skip

script:
  - |
    set -e
    if [ "$CI" = "true" ]; then
      echo "Hello, World."
      sleep 10
    fi
  - if [ "$CI" = "true" ]; then echo "Hello, World..." fi
  - sleep 5
