os: linux
language: node_js
install: skip

script:
  - node -v
  - go version
jobs:
  include:
    - dist: focal
      node_js: 16
    - dist: jammy
      node_js: 16
    - dist: focal
      node_js: 18
    - dist: focal
      node_js: 18
