os: linux
language: node_js
install: skip

script:
  - node -v
  - go version
  - psql --version
jobs:
  include:
    - dist: jammy
      node_js: 16
      services:
        - postgresql
      addons:
        postgresql: "15"
