os: linux
dist: xenial

language: node_js
node_js: 16
install: skip
script: ruby -v

jobs:
  include:
    - dist: focal
      services:
        - rabbitmq
    - dist: xenial
      addons:
        apt:
          packages:
            - rabbitmq-server
