language: ruby
ruby: 3.2.2
os: linux
install: skip
script:
  - ruby --yjit --version
  - |
    echo "TRAVIS_TAG: ${TRAVIS_TAG}"
    echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
#deploy:
#  provider: releases
#  token: $GITHUB_OAUTH_KEY
#  file: Makefile
#  edge: true
#  skip_cleanup: true
#  on:
#    tags: true
#    branch: minimal-build-check
