language: node_js
jobs:
  include:
    - os: linux
      dist: focal
      node_js: lts/*
      install: skip
      script: node -v
      
    - os: linux
      dist: xenial
      node_js: 14
      install: skip
      script: node -v
      
    - os: linux
      dist: xenial
      node_js: 12
      install: skip
      script: node -v
