os: linux
dist: focal
language: ruby
ruby: 2.7.6

services:
  - postgresql
addons:
    postgresql: 12
    apt:
      update: true
      packages:
        - postgresql-12
        - postgresql-client-12
    chrome: stable
    
install: skip
script: true
