os: linux
language: php

install: skip
script: true

jobs:
  include:
    - dist: xenial
      php: 8.1.21
    - dist: bionic
      php: 8.1.21
    - dist: focal
      php: 8.1.21
    - dist: jammy
      php: 8.1.21
        
