os: linux
dist: focal
language: node_js
node_js: 18

install: yarn --frozen-lockfile --verbose
script: sleep 1

jobs:
  include:
    - arch: amd64
    - arch: s390x
    - arch: ppc64le
    - arch: arm64
