os: linux
dist: bionic
group: edge
arch: Arm64

language: shell

install: skip
script: true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: hello.md
  skip_cleanup: true
  on:
    tags: true
