language: shell

before_install:
  - nvm install 16 && nvm use 16
  - pyenv install 3.8.8 && pyenv global 3.8.8

install: skip

script:
  - chmod +x python-version
  - chmod +x node-version
  - ./python-version
  - ./node-version
jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
