os: linux
dist: focal
language: generic

services:
  - docker
install: skip
script:
  - df -h
  - nproc
  - free -hm
  - docker images
  - docker system prune --volumes -a
  - sudo systemctl restart docker
  - sleep 5
  - docker pull moussavdb/build-nodejs:lts
  - docker images
  - df -h
  - nproc
  - free -hm
  - sleep 3
jobs:
  include:
    - arch: arm64
      virt: vm
    - arch: arm64-graviton2
      group: edge
      virt: lxd
    - arch: amd64
