---
language: node_js
node_js: 16
os:
- linux
dist: focal
arch:
- arm64
env:
  global:
    - NODE_OPTIONS: "--dns-result-order=ipv4first"
jobs:
  fast_finish: true
  include:
    - services:
        - xvfb
      before_install: sleep 1
      install: skip
      script: sleep 1
      after_success: sleep5
      after_failure: sleep 10
    - before_install: sleep 2
      install: skip
      script: sleep 2
      after_success: sleep5
      after_failure: sleep 10
    - before_install: sleep 3
      install: skip
      script: sleep 3
      after_success: sleep5
      after_failure: sleep 10
before_script: sleep 5

