language: shell

os: osx

before_install:
  - git clone https://qasim-at-tci:$GITHUB_TOKEN@github.com/test-runs-tci/tci-pvt-builds.git
script:
  - python -V
  - pip -V

jobs:
  include:
    - osx_image: xcode13.1
    - osx_image: xcode13.2
    - osx_image: xcode13.3
      before_install:
        - alias python=/usr/local/bin/python3
        - alias pip=/usr/local/bin/pip3
    - osx_image: xcode14.2
      before_install:
        - alias python=/usr/local/bin/python3
        - alias pip=/usr/local/bin/pip3
