os: linux
dist: focal
language: java
jdk: openjdk11

env:
  global:
    - TARGET_SDK_VERSION=31
    - ANDROID_BUILD_TOOLS_VERSION=31.0.0
    - ANDROID_COMMAND_LINE_TOOLS_VERSION=9477386
    - ANDROID_HOME=~/android-sdk
cache:
  directories:
    # Android SDK
    - $ANDROID_HOME/android-cmdline-tools
    - $ANDROID_HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - wget -O cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_COMMAND_LINE_TOOLS_VERSION}_latest.zip
  - unzip -qq -n cmdline-tools.zip -d $ANDROID_HOME/android-cmdline-tools
  
  - yes | $ANDROID_HOME/android-cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools"
  - yes | $ANDROID_HOME/android-cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;${ANDROID_BUILD_TOOLS_VERSION}"
  - yes | $ANDROID_HOME/android-cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-${TARGET_SDK_VERSION}"
  
  #- chmod +x gradlew
  
#before_script:
# - chmod +x gradlew
script:
 - $ANDROID_HOME/cmdline-tools/bin/sdkmanager --version --sdk_root=$ANDROID_HOME
 - $ANDROID_HOME/cmdline-tools/bin/sdkmanager --list --sdk_root=$ANDROID_HOME
 - echo done
