os: linux
dist: focal
language: python
python: '3.10'

# SETUP QDRANT START ####################################
before_install:
  - docker pull qdrant/qdrant
  - docker run -p 6333:6333 -p 6334:6334 -d qdrant/qdrant
# SETUP QDRANT END ######################################

script: python qdrant.py