os: linux
arch: amd64

language: csharp
mono: none
dotnet: 6.0.16

install: skip

before_script:
  - dotnet --version
script: true

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
