dist: jammy

language: java
jdk: openjdk17

install: skip

script:
  - java -Xmx32m -version
  - javac -Xmx32m -version

jobs:
  include:
    - before_install: export _JAVA_OPTIONS="-Xms128m -Xmx512m"
    - before_install: export JAVA_TOOLS_OPTIONS="-Xms128m -Xmx512m"
