os: linux
dist: jammy

install: skip

jobs:
  include:
    - arch: amd64
      language: shell
      script:
        - artifacts version
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
