language: java
jdk: openjdk18

install: skip
script:
  - git log

jobs:
  include:
    - arch: amd64
      env: BUILD_ARCH=amd64
    - arch: arm64
      env: BUILD_ARCH=arm64
    - arch: arm64-graviton2
      group: edge
      virt: vm
      env: BUILD_ARCH=arm64
