os: linux
dist: jammy

install: skip

jobs:
  include:
    - arch: arm64
      language: shell
      script: true
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
