os: linux
arch: amd64
dist: focal
language: python

before_install:
  - unset PYENV_ROOT
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - pyenv install 3.12.0b1
  - pyenv global 3.12.0b1

script: python -V
