os: linux
language: php
jobs:
  include:
    - dist: jammy
      php:
        - '8.2.0'

      services:
        - mysql

      addons:
        apt:
          update: true
          packages:
            - libonig-dev
      install: skip
      script: true
