language: php
install: skip
script: true

jobs:
  include:
    - dist: bionic
      php: 8.2snapshot
    - dist: bionic
      php: 8.2
    - dist: focal
      php: 8.2snapshot
    - dist: focal
      php: 8.2
