arch: arm64
os: linux

language: generic

services:
  - docker

install: skip
script:
  - docker pull moussavdb/build-nodejs-arm64
  - docker images
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
