os: linux
dist: jammy
language: node_js
node_js: 14

before_install:
  - sudo apt update && sudo apt install gnupg2 wget -y
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
  - sudo apt update && sudo apt install postgresql-16 postgresql-contrib-16 -y
  - sudo sed -i '/^host/s/ident/md5/' /etc/postgresql/16/main/pg_hba.conf
  - sudo sed -i '/^local/s/peer/trust/' /etc/postgresql/16/main/pg_hba.conf
  - echo "host all all 0.0.0.0/0 md5" | sudo tee -a /etc/postgresql/16/main/pg_hba.conf
  - sudo systemctl restart postgresql@16

install: skip
script: sudo rabbitmqctl status
