##
os: linux
dist: focal
language: shell
install: skip

jobs:
  include:
    - stage: NO-REDIRECTION
      arch: s390x
      script:
        - chmod +x hello.sh
        - ./hello.sh 
    - stage: REDIRECTION-TO-DEV_NULL
      arch: s390x
      script:
        - chmod +x hello.sh
        - ./hello.sh >> /dev/null 2>&1
    - stage: REDIRECTION-TO-FILE
      arch: s390x
      before_script:
        - touch output.txt
      script:
        - chmod +x hello.sh
        - ./hello.sh >> output.txt 2>&1
      after_failure:
        - cat output.txt
      after_success:
        - cat output.txt

    
