---
language: php
php:
- '8.2'
os:
- linux
dist: focal
env:
  global:
  - PGPORT=5433
  #- PGUSER=travis
jobs:
  include:
  - stage: one
    services:
      - postgresql
    #addons:
    #  postgresql: '12'
    #  apt:
    #    packages:
    #      - libonig5
    #      - postgresql-12
    #      - postgresql-client-12
    #      - postgresql-12-postgis-3
    install: skip
    script: psql -c "\l" -d travis
