os: linux
dist: jammy
language: node_js
node_js: 14
addons:
  postgresql: "16"
  apt:
    packages:
    - postgresql-16
    - postgresql-client-16
env:
  global:
  - PGPORT=5433
  - PGUSER=travis

install: skip
script: sudo rabbitmqctl status
