arch: amd64
os: linux
dist: focal

before_install:
  - sudo apt-get install -y aspell aspell-en
  - sudo apt-get install libpng16-16
  - sudo ldconfig
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update

install:
  - sudo apt-get install php7.3 php7.3-mbstring php7.3-xml php7.3-tokenizer php7.3-json php7.3-bcmath php7.3-ctype php7.3-gd php7.3-zip php7.3-pgsql


before_script:
  - php --version
  - php7.3 --version

script: sleep 2
