os: linux
dist: jammy
language: shell
install: skip
script: true

jobs:
  include:
    - arch: amd64
    - arch: Arm64
    - arch: arm64-graviton2
      virt: lxd
      group: edge
    - arch: ppc64le
    - arch: s390x
      virt: lxd
