language: go
arch:
  - arm64
os: linux
go:
  - '1.18'
services:
  - docker

install:
    - ARCH=`uname -p`
    - echo $ARCH
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/arm64/kubectl
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin/kubectl
script:
  - echo Hello
