os: osx
language: shell

install: skip
script: python3 -V

jobs:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
    - osx_image: xcode8.3
    - osx_image: xcode9
    - osx_image: xcode9.1
    - osx_image: xcode9.2
    - osx_image: xcode9.3
    - osx_image: xcode9.4
    - osx_image: xcode10
    - osx_image: xcode10.1
    - osx_image: xcode10.2
    - osx_image: xcode10.3
    - osx_image: xcode11
    - osx_image: xcode11.1
    - osx_image: xcode11.2
    - osx_image: xcode11.3
    - osx_image: xcode11.4
    - osx_image: xcode11.5
    - osx_image: xcode11.6
    - osx_image: xcode12
    - osx_image: xcode12.2
    - osx_image: xcode12.3
    - osx_image: xcode12.4
    - osx_image: xcode12.5
    - osx_image: xcode13.1
    - osx_image: xcode13.2
    - osx_image: xcode13.3
    - osx_image: xcode13.4
    - osx_image: xcode14
    - osx_image: xcode14.1
