---
language: ruby
os:
- linux
dist: focal
env:
  global:
  - PGPORT=5433
  #- PGUSER=travis
jobs:
  include:
  - stage: one
    addons:
      postgresql: '13'
      apt:
        packages:
          - libpq-dev
          - libcurl4-openssl-dev
          - libgmp3-dev
          - postgresql-13
          - postgresql-client-13
    services:
    - postgresql
    install: skip
    script: psql -c "\l" -d travis
