os: linux
dist: jammy
language: shell
install: skip

jobs:
  include:
    - arch: arm64
      script: true
      
deploy:
  provider: releases
  token: "$GITHUB_TOKEN"
  edge: true
  on:
    branch: minimal-build-check
