os: linux
dist: focal
language: python
python:
  - 3.7.7
services:
  - redis
  - mysql

before_install:
  - sudo apt update && sudo apt install curl wget gnupg apt-transport-https -y
  - curl -fsSL https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo gpg --dearmor -o /usr/share/keyrings/erlang.gpg
  - echo "deb [signed-by=/usr/share/keyrings/erlang.gpg] https://packages.erlang-solutions.com/ubuntu $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/erlang.list
  - sudo apt update && sudo apt install erlang -y
  - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
  - sudo apt update && sudo apt install rabbitmq-server -y
  - sudo systemctl start rabbitmq-server.service
install: skip
script: sleep 1
