jobs:
  include:
    - dist: focal
      language: ruby
      ruby: 2.7.6
      addons:
        mariadb: '10.3'
      before_install:
        - sudo apt-get remove --purge mysql-server mysql-client mysql-common
        - sudo apt-get autoremove
        - sudo apt-get autoclean
        - sudo rm -rf /var/lib/mysql
        - sudo rm -rf /etc/mysql
        - sudo apt install mariadb-server mariadb-client -y
        - mysql -V
        - sudo service mysql start
        - sudo service mysql status
      install: skip
      script: true
