os: linux
dist: focal
language: shell
group: dev

services:
  - mongodb

install: skip

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: true
