language: bash

env:
  global:
    - JENKINS_URL=https://test.dev
    - secure: ZisyOl8sKSGVv2jWHNgJe7EhGbcz6oYFvOjhcB7F=
    - secure: JxPB2WKZHTAVaODy7Bgod8KDSpxO+IUcrznhhF4sTGwaal6T=

before_script:
- curl --fail --silent --show-error -O "https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz"
- mkdir helm-v3
- tar zxf helm-v3.4.2-linux-amd64.tar.gz -C helm-v3
- export PATH=$PATH:$PWD/helm-v3/linux-amd64

script: true
