language: shell
os: linux
dist: jammy
jobs:
  include:
    - name: "With Workaround"
      addons:
        apt:
          update: true
          packages:
            - redis
      script:
       - redis-cli --version
    - name: "Without Workaround"
      services:
       - redis-server
      script:
       - redis-cli --version
