os: linux
dist: bionic
language: ruby
ruby: 2.4.8

install: skip
before_install:
  - chmod a+x ./deploy
jobs:
  include:
    - arch: amd64
      group: previous
      script: ruby -v
    - arch: amd64
      group: dev
      script: ruby -v
    - arch: amd64
      group: edge
      script: ruby -v
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
