language: java
env:
  global:
    - GRADLE_HOME="$PWD/gradle-7.4"
    - PATH=$GRADLE_HOME/bin:$PATH
install: skip
before_script:
  - wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
  - unzip -qq gradle-7.4.2-bin.zip
script:
  - ./gradlew -q dependencies
  - ./gradlew run --refresh-dependencies
  

jobs:
  include:
    - jdk: openjdk11
      dist: jammy
