os: linux
dist: bionic
group: edge
arch: Arm64

language: cpp

install: skip
script: true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: test.md
  skip_cleanup: true
  on:
    tags: true
