arch: arm64
os: linux

language: shell

services:
  - docker

install: skip
script:
  - docker pull moussavdb/build-nodejs:lts
  - docker images
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
