os: linux
language: shell

addons:
    apt:
      update: true
      packages:
        - libu2f-udev
        - libvulkan1
    chrome: stable
before_install: sudo apt install -f -y    
install: skip
script: true

jobs:
  include:
    - dist: focal
    - dist: xenial
    - dist: bionic
