os: linux
dist: focal
language: python
python:
  - 3.7.7
services:
  - redis
  - mysql

before_install:
  - sudo apt update && sudo apt install curl gnupg -y
  - curl -fsSL https://packages.rabbitmq.com/gpg | sudo apt-key add -
  - sudo add-apt-repository 'deb https://dl.bintray.com/rabbitmq/debian focal main'
  - sudo apt update && sudo apt install rabbitmq-server -y
  - sudo systemctl start rabbitmq-server
install: skip
script: sleep 1
