os: linux
arch: amd64

language: python

before_install:
  - pyenv update
  - pyenv install 3.12.0b1
  - pyenv global 3.12.0b1

script: python -v

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
