os: linux
dist: focal
language: shell
install: skip
script: sleep 1
deploy:
  edge: true
  - provider: elasticbeanstalk
    on:
      branch: dev

  - provider: elasticbeanstalk
    on:
      branch: stage

  - provider: elasticbeanstalk
    on:
      branch: master

  - provider: elasticbeanstalk
    on:
      branch: minimal-build-check
