os: linux
language: ruby
ruby: 2.7.6
addons:
  chrome: stable

before_install: sudo apt install -f -y
install: skip
script: true

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
