language: generic
dist: focal
services:
  - docker
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
install: skip
script: sleep 2
