os: linux
language: python

install: pip install -r requirements.txt

jobs:
  include:
    - name: "Python 3.7"
      dist: jammy
      python: 3.7.15
      script: true
    - name: "Python 3.8"
      dist: jammy
      python: 3.8.16
      script: true
    - name: "Python 3.9"
      dist: jammy
      python: 3.9.16
      script: true
    - name: "Python 3.10"
      dist: jammy
      python: 3.10.9
      script: true
    - name: "Python 3.11"
      dist: jammy
      python: 3.11.2
      script: true
