dist: focal
language: shell
services:
  - docker
env:
  global:
    DOCKER_COMPOSE_VERSION: v2.17.3

before_install:
  - uname -a
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install: skip

script:
  - docker-compose version
  - docker-compose up

jobs:
  include:
    - arch: arm64
    - arch: arm64-graviton2
      group: edge
      virt: lxd
    - arch: arm64-graviton2
      group: edge
      virt: vm
