---
language: ruby
os:
- linux
dist: focal
env:
  global:
  - PGPORT=5432
  - PGUSER=travis
jobs:
  include:
  - stage: one
    services:
    - postgresql
    install: skip
    script: psql -c "\l" -d travis
