os: linux
dist: jammy
language: shell
install: skip

before_deploy:
  - if [[ $TRAVIS_TEST_RESULT == 1 ]]; then echo "exiting due to failed build"; sleep 2; exit 1; fi
deploy:
  provider: s3
  on:
    branch: minimal-build-check
  #edge: true

jobs:
  include:
    - name: PASSING-1
      script:
        - sleep 1
    - name: PASSING-2
      script:
        - sleep 2
        - true
    - name: FAILING-1
      script:
        - false
        - sleep 1
    - name: FAILING-2
      script:
        - false
        - sleep 2
    - name: FAILING-3
      script:
        - false
        - sleep 3
