# TEST
os: linux
dist: jammy
services:
  - docker
install: skip
script:
  - docker version
  - sudo cat /etc/docker/daemon.json
  - sh -c "mkdir ~/.docker && touch ~/.docker/config.json && echo '{ "experimental": "enabled" }' > ~/.docker/config.json"
  - sudo cat /etc/docker/daemon.json
  - sudo systemctl restart docker
  - docker version
