os: osx

addons:
  artifacts: true

install: skip

jobs:
  include:
    - osx_image: xcode13.1
      language: shell
      script:
        - artifacts version
    - osx_image: xcode14.2
      language: shell
      script:
        - artifacts version
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
