os: linux
vm:
  size: 2x-large
install: skip

script:
  - free -hm
  - nproc

jobs:
  include:
    - dist: bionic
      language: ruby
      ruby: 2.4.8
    - dist: focal
      language: php
      php: 8.2
    - dist: focal
      language: python
      python: 3.8
