dist: focal
arch: amd64

services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

language: php
php: 8.3
install: skip

script:
  - php -v
  - sudo service postgres restart
  - sleep 2
  - psql --version
