language: shell
install: skip
scripts:
  - docker build -t test-run .
  - docker images | grep 'test-run'
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
    
