os: linux

language: android

install: skip

jobs:
  include:
    - before_install:
        - sudo apt update
        - sudo apt install -y ca-certificates
        - sudo update-ca-certificates
        - sudo sed -i 's/mozilla\/DST_Root_CA_X3.crt/!mozilla\/DST_Root_CA_X3.crt/g' /etc/ca-certificates.conf && sudo update-ca-certificates
      script: true
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
