os: linux
dist: xenial

install: skip
script:
  - node -v
  - php --version
jobs:
  include:
    #- language: generic
    - language: php
      php: 5.6
      nvm: 16
    #- language: ruby
    #  ruby: 2.7.7
