os: linux

install: skip

script: true

jobs:
  include:
    - dist: bionic
      language: ruby
      ruby: 2.4.8
    - dist: focal
      language: php
      php: 8.2
    - dist: focal
      arch: ppc64le
      language: python
      python: 3.8
