os: linux
dist: jammy
language: java
group: edge
install: skip
before_install:
  - wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc |  gpg --dearmor | sudo tee /usr/share/keyrings/mongodb.gpg > /dev/null
  - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
  - sudo apt update
  - sudo apt install mongodb-org -y
  - sudo service mongod start && sleep 15 && sudo service mongod status
script:
  - sudo apt-get update

jobs:
  include:
    - arch: amd64
    - arch: arm64
    - arch: s390x
    - arch: ppc64le
    

#before_deploy:
#  - rvm install 2.7.8 && rvm use 2.7.8 && gem install dpl
#deploy:
#  provider: releases
#  token: $GITHUB_TOKEN
#  edge: true
#  on:
#    branch: minimal-build-check
