os: linux
dist: focal
language: php
php: "8.1.25"
install: skip
script:
  - free -hm
  - nproc
  - grep MemTotal /proc/meminfo
jobs:
  include:
    - vm:
        size: gpu-medium
    - vm:
        size: gpu-xlarge
