#
os: linux
dist: bionic
services:
  - docker
language: shell
arch: ppc64le
install: skip
script:
  - docker run --privileged ubuntu:23.04 echo "Hello, world!"
  - docker run quay.io/podman/stable echo "Hello, world!"
  - docker pull ubuntu:23.04
  - docker images
  - docker run --privileged quay.io/podman/stable echo "Hello, world!"
