arch: arm64
os: linux
dist: focal

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install: skip
script:
  - sudo apt update && sudo apt install uidmap -y -f
  - chmod +x ids
  - sudo ./ids
  - docker run --rm hello-world
  - docker pull moussavdb/build-nodejs:lts
  - docker images
  - sleep 15
jobs:
  include:
    - language: generic
    - language: shell
    - language: ruby
      ruby: 2.7.7
