os: linux
language: generic

services:
  - docker
install: skip
script:
  - docker images
  - docker pull moussavdb/build-nodejs:lts
  - docker images
jobs:
  include:
    - arch: arm64
    - arch: arm64-graviton2
      group: edge
      virt: lxd
    - arch: amd64
