language: php
php: 8.2
os: linux

addons:
  apt:
    update: true
    packages:
    - libonig-dev

install: skip
script: true

jobs:
  include:
    - dist: jammy
    - dist: focal
    - dist: bionic
    - dist: xenial
