os: linux
language: node_js
install: skip

script:
  - node -v
  - go version
  - psql --version
jobs:
  include:
    - dist: jammy
      node_js: 16
      before_script:
        - psql --version
        - sudo apt update && sudo apt install postgresql postgresql-client -y
        - sudo apt install -f -y
