language: shell
os: linux
dist: jammy
group: dev
jobs:
  include:
    - script: sleep 5
      deploy:
        provider: s3
        access_key_id: $ACCESS_KEY_ID
        secret_access_key: $ACCESS_KEY_SECRET
        bucket: bucketzzz
        edge: true
