arch: arm64
virt: vm
os: linux
dist: focal

language: generic

services:
  - docker

install: skip
script:
  - cat /etc/subuid
  - cat /etc/subgid
  - docker pull moussavdb/build-nodejs:lts
  - docker images
