language: python
jobs:
  include:
    - os: linux
      dist: focal
      python: 3.12-dev
      install: skip
      script: node -v
      
    - os: linux
      dist: bionic
      python: 3.11
      install: skip
      script: node -v
      
    - os: linux
      dist: focal
      python: 3.11
      install: skip
      script: node -v
