language: node_js

_prior_versions: &xenial
  os: linux
  dist: xenial
  
_new_versions: &focal
  os: linux
  dist: focal
  node_js: lts/*

jobs:
  include:  
    - <<: *focal
      install: skip
      script: node -v
      
    - <<: *xenial
      node_js: 12
      install: skip
      script: node -v
      
    - <<: *xenial
      node_js: 14
      install: skip
      script: node -v
