language: ruby
ruby: 2.5.3

install: skip
script:
  - ruby -v
  - sleep 5
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: jammy
