language: generic

jobs:
  include:
    - os: linux
      dist: focal
      install: skip
      script: true
      deploy:
        provider: releases
        token: $GH_TOKEN
        file: README.md
        edge: true # opt in to dpl v2
        draft: true
        on:
          branch: minimal-build-check
      
    - os: linux
      dist: jammy
      install: skip
      script: true
      deploy:
        provider: releases
        token: $GH_TOKEN
        file: README.md
        edge: true # opt in to dpl v2
        draft: true
        on:
          branch: minimal-build-check
