os: linux
language: shell
install: skip

before_deploy:
  #- |
  #  if [ $TRAVIS_TEST_RESULT == 1 ]; then
  #    $BUILD=success
  #  fi
  - if [[ ( "$TRAVIS_TEST_RESULT" == 1 ) ]]; then export build=success; fi
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: minimal-build-check
    condition: $BUILD = success

jobs:
  include:
    - name: PASSING
      script: true
    - name: FAILING
      script: false
