addons:
  artifacts: true

install: skip

jobs:
  include:
    - os: osx
      osx_image: xcode13.1
      language: shell
      script:
        - ${TRAVIS_HOME}/bin/artifacts -v
    - os: osx
      osx_image: xcode14.2
      language: shell
      script:
        - ${TRAVIS_HOME}/bin/artifacts -v
    - os: linux
      dist: focal
      language: shell
      script:
        - ${TRAVIS_HOME}/bin/artifacts -v
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
