os: linux
dist: focal
language: php
php: 8.2

services: postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT: 5433
install: skip
script:
  - psql -c "CREATE DATABASE test;"
