os: linux
dist: focal
language: shell
install: skip
script: sleep 1
deploy:
  - provider: elasticbeanstalk
    on:
      branch: dev
    edge: true

  - provider: elasticbeanstalk
    on:
      branch: stage
    edge: true

  - provider: elasticbeanstalk
    on:
      branch: master
    edge: true

  - provider: elasticbeanstalk
    on:
      branch: minimal-build-check
    edge: true
