language: shell

os: osx

env:
  global:
    - ARTIFACTS_KEY="ABCDEFGHI"
    - ARTIFACTS_SECRET="JKLMNOP"
    - ARTIFACTS_BUCKET="my-bucket"
    - ARTIFACTS_PATHS="log/"

before_install:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
script: true
after_script:
  - artifacts upload

jobs:
  include:
    - osx_image: xcode14.2
