os: linux
dist: focal

jobs:
  include:
    - vault:
      token: $VAULT
      api_url: https://vault-east.staging.travis-ci.org
      secrets:
        - abc/foo
    - vault:
      token: $VAULT
      api_url: https://vault-east.staging.travis-ci.org
      secrets:
        - abc/foo

script:
  - echo $ABC_FOO
