os: linux
dist: focal
language: shell
vm:
  size: gpu-medium
install: skip

jobs:
  include:
    - script:
        - free -hm
        - nproc
        - sleep 1
    - script:
        - free -hm
        - nproc
        - sleep 2
