language: minimal
dist: focal

git:
  depth: 5

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - task="nslookup check"
      script:
        - true
    - stage: test
      env:
        - task="duplicate check"
      script:
        - .true
  allow_failures:
    env:
        - task="nslookup check"
