language: generic

before_script:
  - export SFDX=https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
  - mkdir sfdx
  - wget -qO- $SFDX | tar xJ -C sfdx --strip-components 1
  - export PATH=./sfdx/bin:$PATH
jobs:
  include:
    - os: linux
      dist: trusty
      install: skip
      script: sfdx --version
      
    - os: linux
      dist: xenial
      install: skip
      script: sfdx --version
      
    - os: linux
      dist: bionic
      install: skip
      script: sfdx --version
    
    - os: linux
      dist: focal
      install: skip
      script: sfdx --version
      
    - os: linux
      dist: jammy
      install: skip
      script: sfdx --version
