dist: focal
arch: amd64

services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

language: php
php: 8.3
install: skip

script:
  - php -v
  - psql --version
