os: linux
language: shell
install: skip

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: minimal-build-check
    condition: $BUILD = success

jobs:
  include:
    - name: PASSING
      script:
        - sleep 2
        - export BUILD=success
    - name: FAILING
      script:
        - false
        - export BUILD=success
