arch: arm64
os: linux
dist: focal

services:
  - docker

install: skip
script:
  - sudo apt update && sudo apt install uidmap -y -f
  - chmod +x ids
  - sudo ./ids 2> /dev/null
  - cat /etc/subuid
  - cat /etc/subgid
  - docker run --rm hello-world
  - docker pull moussavdb/build-nodejs:lts
  - docker images
  - sleep 15
jobs:
  include:
    - language: generic
    - language: shell
    - language: ruby
      ruby: 2.7.7
