language: ruby
ruby: 3.2.2
os: linux
install: skip
script:
  - ruby --yjit --version
  - |
    echo "TRAVIS_TAG: ${TRAVIS_TAG}"
    echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"

jobs:
  include:
    - stage: "XYZ"
      dist: xenial
    - stage: "XYZ"
      dist: bionic
    - stage: "XYZ"
      dist: focal
    - stage: "XYZ"
      dist: jammy
    - stage: "Deploy"
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_KEY
        file: Makefile
        edge: true
        skip_cleanup: true
        if: TRAVIS_TAG ~= ^v(\d+\.)?(\d+\.)?(\*|\d+)$
        on:
          tags: true
          branch: minimal-build-check
