os: linux
dist: bionic
language: python
python:
  - "3.6"
  
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11-postgis-3
    - gdal-bin
    - redis-server
    - poppler-utils
    - libpoppler-cpp-dev

services:
  - elasticsearch
  - postgresql

script:
  - export PERFIOS_PUBLIC_KEY_PATH=/var/keys/perfios/public
  - export PERFIOS_PRIVATE_KEY_PATH=/var/keys/perfios/private
  - sudo mkdir -p $(dirname $PERFIOS_PRIVATE_KEY_PATH) \ && sudo openssl genrsa -out $PERFIOS_PRIVATE_KEY_PATH 512 \ && sudo -E bash -c 'openssl rsa -in $PERFIOS_PRIVATE_KEY_PATH -pubout > $PERFIOS_PUBLIC_KEY_PATH'
