os: linux
dist: focal
language: generic
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    packages:
      - docker-ce
      - docker-buildx-plugin
git:
  depth: false
branches:
  except:
    - "/^v\\d+.*$/"
services:
  - docker
before_install:
  - docker --version
install: skip
script:
  - docker info
before_deploy: sleep 1
deploy:
  provider: script
  script: ./hello.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|staging|master|minimal-build-check)$
