language: ruby
ruby: 3.1.2

before_install:
  - rvm install 2.6.9
  - rvm use 2.6.9
  - gem install bundler:2.3.7

install: skip
script:
  - ruby -v
  - bundler -v
  - gem -v
  - sleep 5
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: jammy
