dist: focal
language: shell
services:
  - docker

env:
  global:
    DOCKER_COMPOSE_YML: ./docker/docker-compose.travis.yml
    DOCKER_COMPOSE_VERSION: v2.17.3
    TOTAL_FEATURES_CHUNKS: 6
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1

before_install:
  - uname -a
  - docker-compose version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install: skip

script:
  - docker-compose version
  - docker-compose up

jobs:
  include:
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      env:
        - FEATURES_CHUNK=1
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      env:
        - FEATURES_CHUNK=2
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      env:
        - FEATURES_CHUNK=3
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      env:
        - FEATURES_CHUNK=4
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      env:
        - FEATURES_CHUNK=5
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      env:
        - FEATURES_CHUNK=6
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      env:
        - FEATURES_CHUNK=others
    # amd64
    - arch: amd64
      env:
        - FEATURES_CHUNK=1
    - arch: amd64
      env:
        - FEATURES_CHUNK=2
    - arch: amd64
      env:
        - FEATURES_CHUNK=3
    - arch: amd64
      env:
        - FEATURES_CHUNK=4
    - arch: amd64
      env:
        - FEATURES_CHUNK=5
    - arch: amd64
      env:
        - FEATURES_CHUNK=6
    - arch: amd64
      env:
        - FEATURES_CHUNK=others
    
