dist: bionic
install: true
language: cpp
addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
   packages:
  apt_packages:
    - gfortran

before_install:
  - sudo rm -f /etc/apt/sources.list.d/pgdg.list
install: skip
script: sleep 1
