os: linux

jobs:
  include:
    - dist: xenial
      rvm: '2.7.7'
      install: skip
      script: true
    - dist: bionic
      rvm: '2.7.7'
      install: skip
      script: true
    - dist: focal
      rvm: '2.7.7'
      install: skip
      script: true
    - dist: focal
      rvm: '2.7.7'
      install: skip
      script: true
    - dist: jammy
      rvm: '2.7.7'
      install: skip
      script: true
    - dist: xenial
      rvm: '3.0.5'
      install: skip
      script: true
    - dist: bionic
      rvm: '3.0.5'
      install: skip
      script: true
    - dist: focal
      rvm: '3.0.5'
      install: skip
      script: true
    - dist: focal
      rvm: '3.0.5'
      install: skip
      script: true
    - dist: jammy
      rvm: '3.0.5'
      install: skip
      script: true
    - dist: xenial
      rvm: '3.1.3'
      install: skip
      script: true
    - dist: bionic
      rvm: '3.1.3'
      install: skip
      script: true
    - dist: focal
      rvm: '3.1.3'
      install: skip
      script: true
    - dist: focal
      rvm: '3.1.3'
      install: skip
      script: true
    - dist: jammy
      rvm: '3.1.3'
      install: skip
      script: true
