dist: focal
sudo: required
language: shell
jobs:
  include:
  - os: linux
    arch: arm64-graviton2
    group: edge
    vm:
      size: x-large
  - os: linux
    arch: arm64-graviton2
    group: edge
script:
- free -m
- nproc
