jobs:
  include:
    - language: android
      dist: trusty
      android:
        components:
        - tools
        - platform-tools
        - android-32
        - android-22
        - sys-img-armeabi-v7a-android-22
        - sys-img-x86_64-android-22
        - extra-google-m2repository
        - extra-android-m2repository
      jdk: openjdk8
      licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

      before_install:
      - touch $HOME/.android/repositories.cfg
      - jdk_switcher use oraclejdk8
      - yes | sdkmanager "platforms;android-32"

      before_script:
      - echo no | android create avd --force -n test -t android-22 --abi x86_64
      - emulator -avd test -wipe-data -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
      script: true
