language: php
install: skip

script: true

jobs:
  include:
    - php: master
      dist: xenial
    - php: master
      dist: bionic
    - php: master
      dist: focal
    - php: master
      dist: jammy

    - php: 8.0
      dist: xenial
    - php: 8.0
      dist: bionic
    - php: 8.0
      dist: focal
    - php: 8.0
      dist: jammy

    - php: 8.1
      dist: xenial
    - php: 8.1
      dist: bionic
    - php: 8.1
      dist: focal
    - php: 8.1
      dist: jammy

    - php: 8.2
      dist: xenial
    - php: 8.2
      dist: bionic
    - php: 8.2
      dist: focal
    - php: 8.2
      dist: jammy

    - php: 8.3
      dist: xenial
    - php: 8.3
      dist: bionic
    - php: 8.3
      dist: focal
    - php: 8.3
      dist: jammy
