language: python
python:
- '3.6'
install:
- true
script:
- echo "hello world"
deploy:
- provider: pypi
  on:
    branch: minimal-build-check

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
