language: php
os:
- linux
dist: focal
php:
- '7.4'
services:
  - docker

before_install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.12.0/buildx-v0.12.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

install: skip
script:
  - DOCKER_BUILDKIT=1 docker build .
before_deploy:
  - rvm install 3.1.2 && rvm use 3.1.2
deploy:
  provider: codedeploy
  application: xyz
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUILD_BUCKET"
  region: "$AWS_DEFAULT_REGION"
  wait_until_deployed: true
  bundle_type: tar
  edge: true
  on:
    all_branches: true
