os: linux
language: node_js

install: skip
script:
  - nvm_ls

jobs:
  include:
    - dist: xenial
      node_js: 16.20.0
    - dist: bionic
      node_js: 16.20.2
    - dist: focal
      node_js: 20.11.0
    - dist: jammy
      node_js: 20.9.0
