language: ruby
ruby: 3.2.2
install: skip
script:
  - ruby --yjit -v
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
    - dist: jammy
      language: java
      jdk: 11
      script: java -version
