language: php
os:
- linux
dist: focal
php:
- '7.4'
before_install:

install: skip
script:
  - DOCKER_BUILDKIT=1 docker build .
before_deploy:
  - rvm install 3.1.2 && rvm use 3.1.2
deploy:
  provider: codedeploy
  application: xyz
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUILD_BUCKET"
  region: "$AWS_DEFAULT_REGION"
  wait_until_deployed: true
  bundle_type: tar
  edge: true
  on:
    all_branches: true
