language: python
os: linux
python:
  - 3.7.7
services:
  - redis
  - mysql
addons:
  apt:
    packages:
      - rabbitmq-server
install: skip
script: sleep 1

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
