language: ruby
ruby: 2.6.9

before_install:
  #- source ~/.rvm/scripts/rvm
  #- rvm use 2.6.9
  #- rm $(which bundle)
  #- rm $(which bundler)
  - gem install bundler:2.4.9
  - gem update --system
dist: bionic

script: true
