os: linux
###
script:
  - echo $TRAVIS_COMMIT_MESSAGE
# if: commit_message ~= /(no-deploy)/
jobs:
  include:
     - os: linux
       name: "Linux ARM64 Jammy"
       dist: jammy
       arch: arm64
       language: shell
     - os: linux
       name: "Linux ARM64 Jammy"
       dist: jammy
       arch: smd64
       language: shell
