os: linux
dist: focal
services:
  - docker
language: shell
install: skip
script:
  - docker images
  - docker build -t test:0.1 .
  - docker images

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
    
