os: linux
dist: jammy
language: shell

install: skip
before_install:
  - chmod a+x ./deploy
jobs:
  include:
    - arch: amd64
      script: false
      
deploy:
  provider: script
  script: ./deploy
  on:
    branch: minimal-build-check
