os: linux
language: ruby

install: skip

script:
  - ruby -v

jobs:
  include:
    - dist: xenial
      ruby: 2.7.8
    - dist: xenial
      ruby: 3.0.6
    - dist: xenial
      ruby: 3.1.4
    - dist: xenial
      ruby: 3.2.2
      
    - dist: bionic
      ruby: 2.7.8
    - dist: bionic
      ruby: 3.0.6
    - dist: bionic
      ruby: 3.1.4
    - dist: bionic
      ruby: 3.2.2
      
    - dist: focal
      ruby: 2.7.8
    - dist: focal
      ruby: 3.0.6
    - dist: focal
      ruby: 3.1.4
    - dist: focal
      ruby: 3.2.2
      
    - dist: jammy
      ruby: 2.7.8
    - dist: jammy
      ruby: 3.0.6
    - dist: jammy
      ruby: 3.1.4
    - dist: jammy
      ruby: 3.2.2
