language: ruby
ruby: 2.6.5
os: linux

install: skip
before_script:
  - bundle config --delete frozen
  - bundle env
script: true

jobs:
  include:
    - dist: focal
    - dist: bionic
    - dist: xenial
