language: c
os: linux

install: skip
script: true

jobs:
  include:
    - dist: jammy
    - dist: focal
    - dist: bionic
    - dist: xenial

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  edge: true
  file: README.md
  on:
    all_branches: true
