---
language: node_js
node_js: 18
dist: jammy

env:
  global:
    - deploy_import_runs=true
    - deploy_xyz=true
    - deploy_prod=true

branches:
  only:
    - import-runs
    - /^\d+\.\d+(\.\d+)?$/

before_script:
  - sleep 15
  - sleep 3

before_deploy:
  - echo "1 2 3"
  - sleep 3
  - echo "4 5 6"
  - sleep 7
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG

import:
  - source: qasim-at-tci/tci-common:common.yml@main
    mode: deep_merge_append
  - source: qasim-at-tci/tci-common:deploy.yml@main
    mode: deep_merge_prepend
  - source: qasim-at-tci/tci-common:node/common.yml@main
    mode: deep_merge_append
