language: ruby
ruby: 2.7.7

install: skip
script:
  - chmod a+x install_gsdk
  - ./install_gsdk
  - sleep 5
jobs:
  include:
    - os: osx
      osx_image: xcode14.2
    - os: linux
      dist: focal
    - os: linux
      dist: jammy
