os: linux

language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - mvn clean install -DskipTests=true
script: java -cp target/hello-world-1.0.0.jar helloworld.HelloWorld

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
