os: linux
dist: jammy

language: java
jdk: openjdk11

install: skip

jobs:
  include:
    - before_install:
        - curl https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-util-klib/1.8.20/kotlin-util-klib-1.8.20.jar --output kotlin-util-klib-1.8.20.jar
      script: true
    - before_install:
        - curl http://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-util-klib/1.8.20/kotlin-util-klib-1.8.20.jar --output kotlin-util-klib-1.8.20.jar
      script: true
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
