os: linux
dist: focal
language: php
php:
  - 7.3.33
before_install:
  - chmod +x ./hello.sh
  - chmod +x ./deploy.sh
install: skip
script: true
deploy:
  provider: script
  script: ./deploy.sh
  cleanup: false
  edge: true
  on:
    all_branches: true
after_failure: ./hello.sh
