os: linux
arch: amd64
language: go
dist: xenial
sudo: true
services:
  - docker
install: skip
script:
  - curl -o /tmp/installer.sh https://raw.githubusercontent.com/travis-ci/travis-enterprise-worker-installers/ga-focal/installer.sh
  - sleep 5
  - echo 'hello'
  - curl https://team-support.travis-ci-enterprise.com/
  - sleep 5

jobs:
  include:
    - name: with-edge
      virt: lxd
      group: edge
    - name: without-edge
      virt: lxd
