sudo: required
language: go
env:
  global:
    - GO111MODULE=on
go:
  - 1.16.6
install: skip
script:
  - docker images
  - docker pull ubuntu:jammy
  - docker images
jobs:
  include:
    - dist: trusty
    - dist: xenial
