os: linux
dist: focal
language: node_js
node_js: lts/*

before_install:
  - python -V
  - python3 -V
  - which python
  - which python3
  #- pyenv install 3.9.18
  #- pyenv global 3.9.18

script:
  - python3.9 comm.py
