# TEST
os: linux
dist: jammy
services:
  - docker
install: skip
script:
  - docker version
  - sudo cat /etc/docker/daemon.json
  - echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json
  - sudo systemctl restart docker
  - docker version
