language: php
# php: 8.2.0
install: skip
script: true

addons:
  apt:
    update: true
    packages:
    - libonig-dev

jobs:
  include:
    - dist: bionic
      php: 8.2.0
    - dist: focal
      php: 8.2.0
    - dist: bionic
      php: 8.2snapshot
    - dist: focal
      php: 8.2snapshot
