dist: bionic
sudo: required
language: java
jobs:
  include:
  - os: linux
    arch: s390x
    jdk: openjdk11
  - os: linux
    arch: ppc64le
    jdk: openjdk11
jdk:
- openjdk11
- openjdk17
- openjdk8

script:
- sleep 1
