os: linux
language: node_js
install: skip

script:
  - node -v
  - go version
  - psql --version
jobs:
  include:
    - dist: jammy
      node_js: 16
      services:
        - postgresql
      addons:
        postgresql: "15"
      before_script:
        - sudo apt update && sudo apt upgrade -y
        - sudo apt install postgresql-15 postgresql-client-15 -f -y
