os: linux
arch: amd64

language: python


before_install: gem install bundler -v 2.4.9

script: python -V

jobs:
  include:
    - dist: xenial
      python: 3.9.16
    - dist: bionic
      python: 3.9.16
    - dist: focal
      python: 3.9.16
    - dist: xenial
      python: 3.10.9
    - dist: bionic
      python: 3.10.9
    - dist: focal
      python: 3.10.9
    - dist: xenial
      python: 3.11.2
    - dist: bionic
      python: 3.11.2
    - dist: focal
      python: 3.11.2
