# Run 5
os: linux
dist: focal

language: php
php: 8.1.27

install: skip
before_script:
  - echo 'memory_limit = 4096M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: sleep 10
