os: linux
dist: xenial
language: python

python:
  - "3.6"

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11-postgis-3
    - gdal-bin
    - redis-server
    - poppler-utils
    - libpoppler-cpp-dev
    
script: true

after_script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - if [[ $TRAVIS_BRANCH == "minimal-build-check" && $TRAVIS_PULL_REQUEST == "false" ]]; then date; fi
