sudo: false
dist: trusty
cache: 
  apt: true
  directories:
    - $HOME/.deps
matrix:
  include:
    - os: osx
      osx_image: xcode13.2
      env: 
      - QF_ARCH=OSX  
      language: c++
      compiler: clang
    - os: linux
      language: c++
      compiler: gcc-4.9
      env: 
      - QF_ARCH=x86  
      addons:
        apt:
          sources:
            - kubuntu-backports
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake
            - build-essential
            - gcc-4.9-multilib
            - g++-4.9-multilib
            - gcc-multilib
            - libgnutls-dev:i386
            - libidn11-dev:i386
            - libkrb5-dev:i386
            - librtmp-dev:i386
            - libpng-dev:i386            
            - libgl1-mesa-dev:i386
            - libglu1-mesa-dev:i386
            - libpulse-dev:i386
            - libsdl2-dev:i386
            - libopenal-dev:i386
            - libfreetype6-dev:i386
            - zlib1g-dev:i386
            - libcurl4-gnutls-dev:i386
            - libglib2.0-dev:i386
    - os: linux
      language: c++
      compiler: clang
      env: 
      - QF_ARCH=x86_64
      addons:
        apt:
          packages:
            - clang
            - cmake
            - build-essential
            - libsdl2-dev
            - libopenal-dev
            - libfreetype6-dev
            - zlib1g-dev
            - libcurl4-gnutls-dev


before_install:
  - if [[ "$QF_ARCH" == "x86" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B; fi

install: skip

script: true
