# .travis.yml
dist: focal

os: linux
language: shell

before_install:
  - sudo apt install curl git
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
  - . "$HOME/.asdf/asdf.sh"
  - asdf plugin-add php https://github.com/asdf-community/asdf-php.git
  - asdf install php 8.2.13

script: php --version
