language: python
python:
- '3.6'
install:
- true
script:
- echo "hello world"
before_deploy:
- curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
- python get-pip.py
- python -m pip install --upgrade "pip < 21.0"
deploy:
- provider: pypi
  on:
    branch: minimal-build-check

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
