os: linux
dist: focal

language: php
php: 8.1

before_install:
  - sudo fallocate -l 4G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - sudo sysctl vm.swappiness=10
  - sudo sysctl -w vm.max_map_count=1966080

install: skip
script: sleep 10
