dist: focal

jdk: openjdk17
#scala:
#  - 2.13.9
git:
  depth: false
before_install:
  - rvm reload
  - rvm install 3.1.2
  - ruby -v
  - redis-cli --version
  - psql --version

services:
  - postgresql
  - redis-server
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

stages:
  - A
  - B
  - C

jobs:
  include:
    - stage: A
      name: "A"
      script:
       - sleep 1
    - stage: B
      name: "B"
      script:
        - sleep 2
    - stage: C
      name: "C"
      if: type != pull_request AND branch = minimal-build-check
      script: sleep 3
