os: linux
dist: focal
language: python
python: 3.7
_job_one_vars: &job_one_vars
  env:
    - var_one=ONE
    - var_two=TWO
    - var_three=THREE
_job_two_vars: &job_two_vars
  env:
    - one=ONE
    - two=TWO
    - three=THREE
jobs:
  include:
  - os: linux
    arch: amd64
    <<: *job_one_vars
    stage: branch
    script: sleep 1

    if: type = push
  - os: linux
    arch: amd64
    <<: *job_two_vars
    stage: PR
    script: sleep 2

    if: type = pull_request
  - os: linux
    arch: amd64
    stage: "deploy"
    name: "dpl v1 - LINUX"
    script: sleep 2
    deploy:
      provider: pypi
      username: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: "DIST"
      on:
        branch: "minimal-build-check"
      #edge: true
  - os: linux
    arch: amd64
    stage: "deploy"
    name: "dpl v2 - LINUX"
    script: sleep 2
    deploy:
      provider: pypi
      username: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: "DIST"
      on:
        branch: "minimal-build-check"
      edge: true
  - os: osx
    osx_image: xcode14.2
    language: shell
    stage: "deploy"
    name: "dpl v1 - OSX"
    script:
      - alias python=python3
      - sleep 2
    deploy:
      provider: pypi
      username: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: "DIST"
      on:
        branch: "minimal-build-check"
      #edge: true
  - os: osx
    osx_image: xcode14.2
    language: shell
    stage: "deploy"
    name: "dpl v2 - OSX"
    script:
      - alias python=python3
      - sleep 2
    deploy:
      provider: pypi
      username: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: "DIST"
      on:
        branch: "minimal-build-check"
      edge: true
notifications:
  slack:
    secure: fB1VQZX1Sekok/MtNh7usFpfNeqiN9lwu2piA9c2lfRXk+EswhM3VPsou/FyaE+D50W/sXhWgY+E/JOCbu3EVl/4pvPjvGuIm9tIqTY3l60G+byJ0/0rz9p2dN9tb5SeoSeRsql6K4s1BFubPdfJe8G9tV4Jc8muiDGcijAGJRNfwSInXorWGh7/DgJBgyMFpgO1QZ84hWRNfgGo5G9ZBO1zEyUMu+UyrvVAgNFGJcLwhMm1e/q2sYtCsmWTeZ3dPDV6shtmGkoIQp9M0w84lCf1+FDGkAwxaGUFpTR1O04u15dGflrW5D/YwfRKTNP4zmyMEaUw8kKZ8CO6vkp4DAMJcIhgmREJmJBOvoUd+aV2z2u/arwGRvTQy75s1dEpELXF48anqqHku3Mm8vh7jFKTmtqayy9iErbVH+Msf+d2NORxDaxKJhM32Y+Anfe+N3aVGtnI9zfdeFPhIX4avYolMPIO2NjXys3zFx5pO9+HzsgeVEUEKuLuSzN2ssndpfU6LnFxl29BEzl3SpDfn3jTVgwJnfdj8NSl6MIOqPAgz0bIW2UoCs2ztV6GvuPArIGt+yCFN7k8s5V081jQsm+svvO+qVebdYJmf5wPfJEHrFeMzRXxrHr7M4DugSHhkfLmtnNLU30b28oNzyunTR/eGtaBD14T2JJLbkFgy3o=

