language: php
php: 8.1
install: skip
script:
  - echo $COMPOSER_HOME
  - composer install
  - composer self-update --rollback
  - php test.php
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
