language: android
dist: trusty
jdk: openjdk17

android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-android-m2repository
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - cd /opt/pyenv/plugins/python-build/../.. && git pull && cd -
  - pyenv install 3.6.15
  - pyenv global 3.6.15
install: skip
script:
  - python -V
  
