language: shell
os: linux
dist: jammy
jobs:
  include:
    - name: "Stable Group"
      script: sleep 5
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_KEY
        file: Makefile
        edge: true
        skip_cleanup: true
        on:
          branch: minimal-build-check
    - name: "Dev Group"
      group: dev
      script: sleep 5
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_KEY
        file: Makefile
        edge: true
        skip_cleanup: true
        on:
          branch: minimal-build-check
