language: shell

before_install:
  - nvm install 16 && nvm use 16
  - pyenv install 3.8 && pyenv global 3.8

install: skip

script:
  - python -V
  - node -v
jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
