os: linux
arch: amd64
language: go
dist: xenial
sudo: true
services:
  - docker
install: skip
script: true

jobs:
  include:
    - name: with-edge
      virt: lxd
      group: edge
    - name: without-edge
      virt: lxd
