language: ruby
ruby: 2.5.3
virt: lxd
install: skip
script:
  - ruby -v
  - sleep 5
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: jammy
      language: shell
      before_install:
        - rvm pkg install openssl
        - rvm install 2.5.3 --with-openssl-dir=/home/$(whoami)/.rvm/usr --disable-binary
        - gem install bundler
