os: linux
dist: focal
language: java
jdk: openjdk11

env:
  global:
    - TARGET_SDK_VERSION=31
    - ANDROID_BUILD_TOOLS_VERSION=31.0.0
    - ANDROID_HOME=~/android-sdk
cache:
  directories:
    # Android SDK
    - $ANDROID_HOME/android-cmdline-tools
    - $ANDROID_HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get update -y
  - sudo apt --only-upgrade install -y ca-certificates
  - sudo update-ca-certificates
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME
  
  #- chmod +x gradlew
  
#before_script:
# - chmod +x gradlew
script:
 - $ANDROID_HOME/cmdline-tools/bin/sdkmanager --version --sdk_root=$ANDROID_HOME
 - $ANDROID_HOME/cmdline-tools/bin/sdkmanager --list --sdk_root=$ANDROID_HOME
 - echo done
