dist: bionic
install: true
language: cpp
before_install:
  - sudo rm -f /etc/apt/sources.list.d/pgdg.list
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-get update -y
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install gfortran
install: skip
script: sleep 1
