os: linux
dist: xenial
language: ruby
ruby: 2.4.8

install: skip
before_install:
  - chmod a+x ./deploy
jobs:
  include:
    - arch: amd64
      script: ruby -v
      
#deploy:
#  provider: script
#  script: ./deploy
#  on:
#    branch: minimal-build-check
