language: ruby
ruby: 2.6.5

before_install:
  - gem update --system 3.0.6
  - gem install bundler:2.4.7

install: skip
script:
  - ruby -v
  - bundler -v
  - gem -v
  - sleep 5
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: jammy
