language: python
os: linux
python:
  - 3.7.7
services:
  - redis
  - mysql

before_install:
  - sudo apt update && sudo apt install rabbitmq-server -y
  - sudo systemctl start rabbitmq-server
install: skip
script: sleep 1

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
