language: shell
os: linux
dist: jammy
group: dev
jobs:
  include:
    - script: sleep 5
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: bucketzzz
        edge: true
