language: php
php: 8.1
env:
  global:
    - COMPOSER_HOME=/home/travis/.config/composer
    - COMPOSER_BIN_DIR=/home/travis/.config/composer/vendor/bin
install: skip
script:
  - echo $COMPOSER_HOME
  - composer install
  - composer self-update --rollback
  - php test.php
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
