os: linux

language: go
go:
  - 1.18.x

install: skip
script:
  - cat /sys/module/kvm_amd/parameters/nested
  - cat /sys/module/kvm_intel/parameters/nested
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
