language: node_js
node_js: 18
dist: jammy

import:
  - source: qasim-at-tci/tci-common:common.yml@main
    mode: deep_merge_append
  - source: qasim-at-tci/tci-common:js/common.yml@main
    mode: deep_merge_append
  - source: qasim-at-tci/tci-common:deploy_.yml@main
    mode: deep_merge_prepend

before_script:
  - sleep 15

before_deploy:
  - echo "1 2 3"
  - sleep 3
  - echo "4 5 6"
  - sleep 7
