os: linux
language: generic

services:
  - docker

install: skip
script:
  - docker build --tag test-image .
  - docker images
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
