os: linux
dist: jammy
language: shell

install: skip
script:
  - sudo apt-get update

jobs:
  include:
    - arch: adm64
    - arch: arm64
    - arch: s390x
    - arch: ppc64le
    

#before_deploy:
#  - rvm install 2.7.8 && rvm use 2.7.8 && gem install dpl
#deploy:
#  provider: releases
#  token: $GITHUB_TOKEN
#  edge: true
#  on:
#    branch: minimal-build-check
