os: osx
language: node_js

install: skip
script: nvm --version
jobs:
  include:
    - osx_image: xcode14.1
      node_js: 14
    - before_install: sleep 1
      node_js: 14
    - os: linux
      dist: xenial
      node_js: 14
    - os: linux
      dist: bionic
      node_js: 14
    - os: linux
      dist: focal
      node_js: 14
    - os: linux
      dist: jammy
      node_js: 14
    
    
