os: linux
dist: bionic
language: ruby
ruby:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - 2.3.8
  
  - 2.4.0
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - 2.4.6
  - 2.4.7
  - 2.4.8
  - 2.4.9
  - 2.4.10
  
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.5
  - 2.5.6
  - 2.5.7
  - 2.5.8
  - 2.5.9
#install: skip
script: true

#jobs:
#  include:
#    - arch: arm64
#      script: true
#    - arch: amd64
#      script: true

#before_deploy:
#  - rvm install 2.7.8 && rvm use 2.7.8 && gem install dpl
#deploy:
#  provider: releases
#  token: $GITHUB_TOKEN
#  edge: true
#  on:
#    branch: minimal-build-check
