jobs:
  include:
    - os: osx
      osx_image: xcode12.5
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      language: c
      compiler: 
        - gcc
      script: true
      addons:
        homebrew:
          packages:
            - bison
            - flex
          update: true
