dist: focal
arch: arm64-graviton2
virt: lxd
group: edge
language: shell
services:
  - docker

before_install:
  # Latest docker
  - uname -a
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install: skip

script:
  - docker compose version
  - docker compose up
