os: linux
language: python

install: pip install -r requirements.txt

jobs:
  include:
    - name: "Jammy"
      dist: jammy
      python: 3.10.5
      script: true
    - name: "Focal"
      dist: focal
      python: 3.10.5
      script: true
