language: java
env:
  global:
    - GRADLE_HOME="$PWD/gradle-8.0.2"
    - PATH=$GRADLE_HOME/bin:$PATH
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2,TLSv1,TLSv1.1
install: skip
before_script:
  - wget https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
  - unzip -qq gradle-8.0.2-bin.zip
script:
  - ./gradlew -q app:dependencies
  - ./gradlew run --refresh-dependencies
  

jobs:
  include:
    - jdk: openjdk11
      dist: jammy
