os: linux
language: node_js
install: skip

script:
  - node -v
  - go version
jobs:
  include:
    - dist: focal
      node_js: 16
      before_script:
        - go version
        - gimme 1.18.3
        - source ~/.gimme/envs/go1.18.3.env
    - dist: jammy
      node_js: 16
    - dist: focal
      node_js: 18
      before_script:
        - go version
        - gimme 1.18.3
        - source ~/.gimme/envs/go1.18.3.env
    - dist: jammy
      node_js: 18
