arch: arm64
dist: focal
language: shell
sudo: required
services:
  - docker
env:
  global:
    DOCKER_COMPOSE_VERSION: 2.17.3
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-aarch64 -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
install: skip
script:
  - docker-compose version
  - docker-compose up
