os: osx
osx_image: xcode12.3
install: skip

jobs:
  include:
    - language: shell
      script:
        - sleep 30
    - language: shell
      script:
        - sleep 31
    - language: shell
      script:
        - sleep 32
    - language: shell
      script:
        - sleep 33
    - language: shell
      script:
        - sleep 34
    - language: shell
      script:
        - sleep 35
