os: linux
language: ruby

addons:
    apt:
      update: true
      packages:
        - libu2f-udev
        - libvulkan1
    chrome: stable
    
install: skip
script: true

jobs:
  include:
    - dist: focal
    - dist: xenial
    - dist: bionic
