# TEST RUN
os: osx
osx_image: xcode12.3
install: skip

jobs:
  include:
    - stage: ONE
      os: linux
      dist: focal
      language: shell
      script:
        - sleep 30
    - stage: TWO
      os: linux
      dist: focal
      language: shell
      script:
        - sleep 21
    - stage: THREE
      language: shell
      script:
        - sleep 11
