language: php
install: skip

script: true

jobs:
  include:
    - php: master
      dist: xenial
    - php: master
      dist: bionic
    - php: master
      dist: focal
    - php: master
      dist: jammy

    - php: nightly
      dist: xenial
    - php: nightly
      dist: bionic
    - php: nightly
      dist: focal
    - php: nightly
      dist: jammy
