os: linux
arch: amd64
language: go
dist: xenial
sudo: true
services:
  - docker
install: skip
script:
  - curl -sSL -o /tmp/installer.sh https://raw.githubusercontent.com/travis-ci/travis-enterprise-worker-installers/ga-focal/installer.sh

jobs:
  include:
    - name: with-edge
      virt: lxd
      group: edge
    - name: without-edge
      virt: lxd
