os: linux
dist: xenial

install: skip
script:
  - node -v
  - php --version
jobs:
  include:
    #- language: generic
    - language: node_js
      node_js: 16
    #- language: ruby
    #  ruby: 2.7.7
