os: linux
dist: focal

script:
  - echo "I scream and I SHOUT" 1>&2

jobs:
  include:
    - language: c
      arch: s390x
    - language: c
      arch: ppc64le
    - language: shell
      arch: s390x
    - language: shell
      arch: ppc64le
