os: linux
dist: focal
language: shell

install: skip

before_script: echo $travis_internal_ruby

script: true

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: CHANGELOG-EXAMPLE.md
  edge: true # opt in to dpl v2
  on:
    branch: minimal-build-check
