os: linux
language: ruby
ruby: 3.1.2
dist: xenial

#before_install:
#- mkdir -p $HOME/bin
#- wget https://github.com/git-lfs/git-lfs/releases/download/v3.3.0/git-lfs-linux-amd64-v3.3.0.tar.gz
#- tar xvfz git-lfs-linux-amd64-v3.3.0.tar.gz
#- mv git-lfs-3.3.0/git-lfs $HOME/bin/git-lfs
#- export PATH=$PATH:$HOME/bin/

install: skip

script:
  - git lfs --version
