os: linux
dist: xenial

install: skip
before_script:
  - nvm use 10
script:
  - node -v
  - php --version
jobs:
  include:
    #- language: generic
    - language: php
      php: 5.6
    #- language: ruby
    #  ruby: 2.7.7
