## Test Run
language: shell
os: linux
dist: focal
jobs:
  include:
    - name: "Without docker service"
      script:
        - docker version
    - name: "With docker service"
      services:
        - docker
      script: docker version
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_KEY
        file: Makefile
        edge: true
        skip_cleanup: true
        on:
          tags: true
          branch: minimal-build-check
