jobs:
  include:
    - dist: focal
      language: ruby
      ruby: 2.7.6
      addons:
        mariadb: '10.3'
      install: skip
      script: true
    - dist: bionic
      language: ruby
      ruby: 2.7.6
      addons:
        mariadb: '10.3'
      install: skip
      script: true
