os: linux
dist: focal
language: php
php: 8.2

services: postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT: 5433
    - DB_NAME: 'xyz'
    - SQL_CREATE_DB: "CREATE DATABASE $DB_NAME;"
    - DB_USER: 'travis'
    - DB_CMD: "psql -U $DB_USER -c"
install: skip
script:
  - $DB_CMD "$SQL_CREATE_DB"
  - $DB_CMD "ALTER USER $DB_USER SET bytea_output = 'escape';"
  - psql -c "\l"
  - psql -c "\du"
