---
language: python
os:
- linux
dist: jammy
python:
- '3.9'
jobs:
  include:
  - stage: one
    addons:
      postgresql: '13'
      apt:
        packages:
        - libssl-dev
        - libxmlsec1
        - libxmlsec1-dev
        - libxmlsec1-openssl
        - postgresql-14
        - postgresql-client-14
        - postgresql-contrib-14
    services:
    - postgresql
    install: skip
    script: sleep 5
