os: linux
dist: focal
language: php
php: 8.1

before_install:
  - ls $HOME/.phpenv
  - git clone https://github.com/php-build/php-build.git $HOME/.phpenv/plugins/php-build
  - phpenv install 8.2snapshot
  - phpenv global 8.2snapshot
install: skip

script: php --version
