os: linux
dist: focal
language: shell
env:
  global:
    - BAR=truea

addons:
  apt:
    packages:
      - ca-certificates

install: skip

jobs:
  include:
    - name: "condition with regex"
      script: echo "condition with regex"
      if: $BAR =~ /^(?i)(true|1).*$/
    - name: "condition-without-regex"
      script: echo "condition without regex"
      if: $BAR =~ [ABC]
