dist: focal
arch: arm64
language: shell
sudo: required
services:
  - docker
env:
  global:
    DOCKER_COMPOSE_VERSION: v2.17.3
  matrix:
    - FEATURES: A
    - FEATURES: B
    - FEATURES: C
    - FEATURES: D
    - FEATURES: E
    - FEATURES: F
    - FEATURES: OTHERS

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install: skip

script:
  - docker-compose version
  - docker-compose up

jobs:
  include:
    - arch: arm64
