os: linux
dist: xenial
language: python

python:
  - "3.6"
  
script: true

after_script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - if [[ $TRAVIS_BRANCH == "minimal-build-check" && $TRAVIS_PULL_REQUEST == "false" ]]; then date; fi
