language: python

script: 
    - wget https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64 && mv ./datadog-ci_linux-x64 /usr/local/bin/datadog-ci && chmod +x /usr/local/bin/datadog-ci
install: skip

jobs:
    include:
        - dist: xenial
        - dist: bionic
        - dist: focal
        - dist: jammy
