# .travis.yml
dist: xenial

os: linux
language: shell

services:
  - docker
before_install:
  - docker version
  - travis_wait 50 docker build -t qasim/test .
  - docker images

script: docker images
