os: linux
dist: focal
language: node_js

env:
  global:
    - NODE_OPTIONS="--dns-result-order=ipv4first"

script: sleep 1

jobs:
  allow_failures:
    - node_js: 12
    - node_js: 14
  include:
    - stage: "NodeJs lts/* with YARN"
      arch: amd64
      node_js: lts/*
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs lts/* with YARN"
      arch: s390x
      node_js: lts/*
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs lts/* with YARN"
      arch: ppc64le
      node_js: lts/*
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs lts/* with YARN"
      arch: arm64
      node_js: lts/*
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs lts/* with YARN"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: lts/*
      install:
        - yarn --frozen-lockfile --verbose

    - stage: "NodeJs stable with YARN"
      arch: amd64
      node_js: node
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs stable with YARN"
      arch: s390x
      node_js: node
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs stable with YARN"
      arch: ppc64le
      node_js: node
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs stable with YARN"
      arch: arm64
      node_js: node
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs stable with YARN"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: node
      install:
        - yarn --frozen-lockfile --verbose

    - stage: "NodeJs 18 with YARN"
      arch: amd64
      node_js: 18
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 18 with YARN"
      arch: s390x
      node_js: 18
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 18 with YARN"
      arch: ppc64le
      node_js: 18
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 18 with YARN"
      arch: arm64
      node_js: 18
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 18 with YARN"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 18
      install:
        - yarn --frozen-lockfile --verbose

    - stage: "NodeJs 16 with YARN"
      arch: amd64
      node_js: 16
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 16 with YARN"
      arch: s390x
      node_js: 16
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 16 with YARN"
      arch: ppc64le
      node_js: 16
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 16 with YARN"
      arch: arm64
      node_js: 16
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 16 with YARN"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 16
      install:
        - yarn --frozen-lockfile --verbose

    - stage: "NodeJs 14 with YARN"
      arch: amd64
      node_js: 14
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 14 with YARN"
      arch: s390x
      node_js: 14
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 14 with YARN"
      arch: ppc64le
      node_js: 14
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 14 with YARN"
      arch: arm64
      node_js: 14
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 14 with YARN"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 14
      install:
        - yarn --frozen-lockfile --verbose

    - stage: "NodeJs 12 with YARN"
      arch: amd64
      node_js: 12
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 12 with YARN"
      arch: s390x
      node_js: 12
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 12 with YARN"
      arch: ppc64le
      node_js: 12
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 12 with YARN"
      arch: arm64
      node_js: 12
      install:
        - yarn --frozen-lockfile --verbose
    - stage: "NodeJs 12 with YARN"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 12
      install:
        - yarn --frozen-lockfile --verbose

    # NPM
    - stage: "NodeJs lts/* with NPM"
      arch: amd64
      node_js: lts/*
      install:
        - npm ci
    - stage: "NodeJs lts/* with NPM"
      arch: s390x
      node_js: lts/*
      install:
        - npm ci
    - stage: "NodeJs lts/* with NPM"
      arch: ppc64le
      node_js: lts/*
      install:
        - npm ci
    - stage: "NodeJs lts/* with NPM"
      arch: arm64
      node_js: lts/*
      install:
        - npm ci
    - stage: "NodeJs lts/* with NPM"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: lts/*
      install:
        - npm ci

    - stage: "NodeJs stable with NPM"
      arch: amd64
      node_js: node
      install:
        - npm ci
    - stage: "NodeJs stable with NPM"
      arch: s390x
      node_js: node
      install:
        - npm ci
    - stage: "NodeJs stable with NPM"
      arch: ppc64le
      node_js: node
      install:
        - npm ci
    - stage: "NodeJs stable with NPM"
      arch: arm64
      node_js: node
      install:
        - npm ci
    - stage: "NodeJs stable with NPM"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: node
      install:
        - npm ci

    - stage: "NodeJs 18 with NPM"
      arch: amd64
      node_js: 18
      install:
        - npm ci
    - stage: "NodeJs 18 with NPM"
      arch: s390x
      node_js: 18
      install:
        - npm ci
    - stage: "NodeJs 18 with NPM"
      arch: ppc64le
      node_js: 18
      install:
        - npm ci
    - stage: "NodeJs 18 with NPM"
      arch: arm64
      node_js: 18
      install:
        - npm ci
    - stage: "NodeJs 18 with NPM"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 18
      install:
        - npm ci

    - stage: "NodeJs 16 with NPM"
      arch: amd64
      node_js: 16
      install:
        - npm ci
    - stage: "NodeJs 16 with NPM"
      arch: s390x
      node_js: 16
      install:
        - npm ci
    - stage: "NodeJs 16 with NPM"
      arch: ppc64le
      node_js: 16
      install:
        - npm ci
    - stage: "NodeJs 16 with NPM"
      arch: arm64
      node_js: 16
      install:
        - npm ci
    - stage: "NodeJs 16 with NPM"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 16
      install:
        - npm ci

    - stage: "NodeJs 14 with NPM"
      arch: amd64
      node_js: 16
      install:
        - npm ci
    - stage: "NodeJs 14 with NPM"
      arch: s390x
      node_js: 14
      install:
        - npm ci
    - stage: "NodeJs 14 with NPM"
      arch: ppc64le
      node_js: 14
      install:
        - npm ci
    - stage: "NodeJs 14 with NPM"
      arch: arm64
      node_js: 14
      install:
        - npm ci
    - stage: "NodeJs 14 with NPM"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 14
      install:
        - npm ci

    - stage: "NodeJs 12 with NPM"
      arch: amd64
      node_js: 12
      install:
        - npm ci
    - stage: "NodeJs 12 with NPM"
      arch: s390x
      node_js: 12
      install:
        - npm ci
    - stage: "NodeJs 12 with NPM"
      arch: ppc64le
      node_js: 12
      install:
        - npm ci
    - stage: "NodeJs 12 with NPM"
      arch: arm64
      node_js: 12
      install:
        - npm ci
    - stage: "NodeJs 12 with NPM"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: 12
      install:
        - npm ci

notifications:
  slack:
    secure: fB1VQZX1Sekok/MtNh7usFpfNeqiN9lwu2piA9c2lfRXk+EswhM3VPsou/FyaE+D50W/sXhWgY+E/JOCbu3EVl/4pvPjvGuIm9tIqTY3l60G+byJ0/0rz9p2dN9tb5SeoSeRsql6K4s1BFubPdfJe8G9tV4Jc8muiDGcijAGJRNfwSInXorWGh7/DgJBgyMFpgO1QZ84hWRNfgGo5G9ZBO1zEyUMu+UyrvVAgNFGJcLwhMm1e/q2sYtCsmWTeZ3dPDV6shtmGkoIQp9M0w84lCf1+FDGkAwxaGUFpTR1O04u15dGflrW5D/YwfRKTNP4zmyMEaUw8kKZ8CO6vkp4DAMJcIhgmREJmJBOvoUd+aV2z2u/arwGRvTQy75s1dEpELXF48anqqHku3Mm8vh7jFKTmtqayy9iErbVH+Msf+d2NORxDaxKJhM32Y+Anfe+N3aVGtnI9zfdeFPhIX4avYolMPIO2NjXys3zFx5pO9+HzsgeVEUEKuLuSzN2ssndpfU6LnFxl29BEzl3SpDfn3jTVgwJnfdj8NSl6MIOqPAgz0bIW2UoCs2ztV6GvuPArIGt+yCFN7k8s5V081jQsm+svvO+qVebdYJmf5wPfJEHrFeMzRXxrHr7M4DugSHhkfLmtnNLU30b28oNzyunTR/eGtaBD14T2JJLbkFgy3o=
