jobs:
  include:
    - os: osx
      osx_image: xcode12.5
      before_cache:
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
      # Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
      # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      language: c
      compiler: 
        - gcc
      script: true
      addons:
        homebrew:
          packages:
            - bison
            - flex
          update: true
