language: node_js

jobs:
  include:
    - name: Job A
      dist: xenial
      node_js: 12
      
    - name: Job B
      dist: xenial
      node_js: 14
      
    - name: Job C
      dist: focal
      node_js: lts/*
      
install: skip
script: true
