os: linux
language: node_js
install: skip

script:
  - node -v
  - go version
  - psql --version
jobs:
  include:
    - dist: jammy
      node_js: 16
      services:
        - postgresql
      before_script:
        - psql --version
        - sudo apt update && sudo apt install postgresql-15 postgresql-client-15 -y
        - sudo apt install -f -y
