# .travis.yml
dist: focal

os: linux

arch: arm64

language: php

php:
  - 8.2.0

services:
  - mysql
  
branches:
  only:
  - minimal-build-check

cache:
  directories:
    - vendor

before_script:
  - mysql --version
  - sleep 1

script: php --version
