os: linux
dist: focal
language: shell

env:
  global:
    - BAR=true
    - FOO=AAA

install: skip

jobs:
  include:
    - name: "condition with regex"
      script: echo $BAR
      if: $BAR =~ ^(?i)(true|1).*$
    - name: "condition-without-regex"
      script: echo $BAR
      if: env(FOO) =~ [ABC]
