os: linux
language: shell

jobs:
  include:
    - install: skip
      script: false

      deploy:
        provider: script
        script: ./deploy
        on:
          branch: minimal-build-check
      if: $TRAVIS_TEST_RESULT = 1
