language: ruby
ruby: 2.6.8

install: skip
script:
  #- chmod a+x install_gsdk
  #- ./install_gsdk
  - ruby -v
  - sleep 3
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: jammy
