dist: focal
language: shell
services:
  - docker

install: skip

script:
  - docker-compose version
  - docker-compose up

jobs:
  include:
    - arch: arm64
    - arch: arm64-graviton2
      group: edge
      virt: lxd
    - arch: arm64-graviton2
      group: edge
      virt: vm
