language: python

python:
  - "3.7"

before_install:
  # multiple versions of setuptools, pip, wheel
  - ls -lt /home/travis/virtualenv/python3.7.13/lib/python3.7/site-packages/
  - ls -lt /home/travis/virtualenv/python3.7.13/lib/python3.7/site-packages/setuptools*
install: skip
script: true
