os: linux
language: ruby
ruby: 3.1.2
dist: xenial

install: skip

before_install:
  - gem install travis

script:
  - travis login --com --github-token $GITHUB_TOKEN
  - travis whoami --com
  - travis status --com --repo test-runs-tci/travis-test-builds
  - travis version
