os: linux
language: php

install: skip
script:
  - php -v

jobs:
  include:
    - dist: xenial
      php: 8.3.2
    - dist: bionic
      php: 8.3.2
    - dist: focal
      php: 8.3.2
    - dist: jammy
      php: 8.3.2

    - dist: xenial
      php: 8.3
    - dist: bionic
      php: 8.3
    - dist: focal
      php: 8.3
    - dist: jammy
      php: 8.3
