language: python

script: 
    - curl https://github.com/DataDog/datadog-ci/releases/download/v2.29.0/datadog-ci_darwin-x64 -o ./datadog-ci && sudo mv ./datadog-ci /usr/local/bin/datadog-ci && sudo chmod +x /usr/local/bin/datadog-ci
    - datadog-ci --version
install: skip

jobs:
    include:
        - dist: xenial
        - dist: bionic
        - dist: focal
