language: cpp
compiler:
  - g++
os: osx
addons:   
  homebrew:
    update: true
    packages:
      - cmake
      - ninja
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
install: skip
script: true

jobs:
  include:
    - osx_image: xcode14.1
    - osx_image: xcode14.2
    - osx_image: xcode14.3
