arch: arm64
os: linux
dist: focal

language: node_js
node_js:
  - 16

before_install:
  - nvm install node
  - node -v
  - npm -v
  - npm i cowsay # without progress set to false
  - npm config set progress=false
  - npm i express # after progress set to true
  - sleep 2
install: skip
script: true
