os: linux
arch: amd64
dist: focal
language: python
script: python -V

jobs:
  include:
    - name: "python 3.12-dev"
      python: 3.12-dev
    - name: "python 3.12.0b1 aka beta 1"
      python: 3.12-beta1
