os: linux
language: shell
jobs:
  include:
    - dist: focal
      install: skip
      script:
        - false # this will make the build fail
  allow_failures: # this will make the build status as passed on a failed build
    - language: shell
