os: linux
dist: focal
language: python
python:
  - 3.7.7
before_install:
  - chmod +x ./hello.sh
install: skip
script: true
deploy:
  provider: script
  script: exec bash; shopt -s nullglob;
  on:
    all_branches: true
after_failure: ./hello.sh
