os: linux
dist: focal
language: shell
install: skip

jobs:
  include:
    - name: "Without docker service"
      services:
        - docker
      script:
        - docker version
        - sleep 7
    - name: "With docker service"
      script:
        - docker version
        - sleep 7
