os: linux
language: ruby

install: pip install -r requirements.txt

jobs:
  include:
    - name: "Ruby"
      dist: xenial
      install: skip
      script:
        - cat /etc/hosts
        - yes | sudo mv ./hosts /etc/hosts
        - cat /etc/hosts
        - ping -c 5 google.com
        
