os: linux
dist: focal
language: php
php: 8.0
before_install:
  - sudo apt-get update && sudo apt-get --purge remove postgresql postgresql-*
  - sudo apt-get install postgresql-9.6 -y
  - sudo psql -c "\du" -d postgres
install: skip
script:
  - sudo psql --version
  - who -m
