language: shell
os: linux
dist: jammy
services:
  - redis
jobs:
  include:
    - name: "Redis"
      script:
        - redis-cli --version
        - redis-cli ping
    - name: "Deploy"
      script: sleep 5
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_KEY
        file: Makefile
        edge: true
        skip_cleanup: true
        on:
          branch: main
