os: linux

language: go
go:
  - 1.18.x

install: skip
script:
  - egrep -c '(vmx|svm)' /proc/cpuinfo
  - sudo kvm-ok
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
