dist: jammy

language: java
jdk: openjdk8

install: skip

script:
  - java -version
  - javac -version

jobs:
  include:
    - before_install: export _JAVA_OPTIONS="-Xms128m -Xmx512m"
    - before_install: export JAVA_TOOLS_OPTIONS="-Xms128m -Xmx512m"
