os: linux
dist: jammy
language: shell

install: skip

jobs:
  include:
    - arch: amd64
      script: false
    - group: dev
      arch: arm64
      script: true
      
deploy:
  provider: script
  script: ./deploy
