---
arch: ppc64le
dist: focal
os: linux
language: shell

script:
    - sudo apt update -y && sudo apt-get install file -y
    - sleep 900 &
    - SCRIPT_PID=$!;while ps -p $SCRIPT_PID > /dev/null;do echo "$SCRIPT_PID is running"; sleep 300; done; wait $SCRIPT_PID; my_pid_status=$?; travis_terminate $my_pid_status
    - sleep 10
