os: linux
language: ruby
group: edge
ruby: 2.6.8

before_install:
  - ruby -v
  - gem install bundler
install: skip

script:
  - ruby -v

jobs:
  include:
    - dist: bionic
    - dist: focal
    - dist: jammy
