---
language: php
php: '8.2'
os: linux
dist: focal

group: dev

env:
  global:
  - PGPORT=5432
  #- PGUSER=travis
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
install: skip
script:
  - psql -c "\l" -d travis
