language: node_js
node_js: 16
os: linux
install: skip
script: java -version

jobs:
  include:
    - dist: xenial
      jdk: openjdk17
    - dist: bionic
      jdk: openjdk17
    - dist: focal
      jdk: openjdk17
    - dist: jammy
      jdk: openjdk17
    #- stage: "Deploy"
    #  deploy:
    #    provider: releases
    #    token: $GITHUB_OAUTH_KEY
    #    file: Makefile
    #    edge: true
    #    skip_cleanup: true
    #    if: TRAVIS_TAG ~= ^v(\d+\.)?(\d+\.)?(\*|\d+)$
    #    on:
    #      tags: true
    #      branch: minimal-build-check
