language: php
php: 8.2
os: linux

install: skip
script: php --version

jobs:
  include:
    - stage: workaround
      dist: jammy
      group: previous
    - stage: workaround
      dist: focal
      group: previous
    - stage: workaround
      dist: bionic
      group: previous
      
    - stage: without-workaround
      dist: jammy
    - stage: without-workaround
      dist: focal
    - stage: without-workaround
      dist: bionic
