arch: arm64
os: linux
dist: focal

services:
  - docker

install: skip
script:
  - sudo apt update && sudo apt install uidmap -y -f
  - cat /etc/subuid
  - cat /etc/subgid
  - python --version
  - python3 --version
  - docker run --rm hello-world
  - docker pull moussavdb/build-nodejs:lts
  - docker images
jobs:
  include:
    - language: generic
    - language: shell
    - language: ruby
      ruby: 2.7.7
